name = "some-recipes"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "some-recipes-db"
database_id = "0b6f91b5-693e-48e8-a84b-edc1533acfee"
migrations_dir = "migrations"
